// Generated by CoffeeScript 1.6.2
(function() {
  var Q, browserify, dirname, extend, fs, isBrowserify, join, once, relative, relativize, resolve, serve, shim, watchify, _ref,
    __slice = [].slice;

  _ref = require('path'), dirname = _ref.dirname, join = _ref.join, resolve = _ref.resolve, relative = _ref.relative;

  fs = require('fs');

  Q = require('kew');

  browserify = require('browserify');

  watchify = require('watchify');

  shim = require('browserify-shim');

  extend = require('xtend');

  relativize = function(entry, requirement, extensions) {
    var expose;

    expose = relative(dirname(entry), requirement);
    expose = expose.replace(/\.[a-z_\-]+$/, '');
    return "./" + expose;
  };

  once = function(func) {
    var called;

    called = false;
    return function() {
      var args;

      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (called) {
        return;
      }
      called = true;
      return func.call.apply(func, [this].concat(__slice.call(args)));
    };
  };

  isBrowserify = function(x) {
    return x && (typeof x === 'object') && (typeof x.bundle === 'function');
  };

  module.exports = serve = function(options) {
    var b, bundle, contentType, rendered, w;

    contentType = options.contentType || 'application/javascript';
    b = serve.bundle(options);
    rendered = void 0;
    bundle = function() {
      rendered = Q.defer();
      return b.bundle(options, once(function(err, result) {
        if (err) {
          return rendered.reject(err);
        } else {
          return rendered.resolve(result);
        }
      }));
    };
    bundle();
    if (options.watch !== false) {
      w = watchify(b);
      w.on('update', bundle);
    }
    return function(req, res, next) {
      res.setHeader('Content-type', contentType);
      return rendered.then(function(result) {
        return res.end(result);
      }).fail(next);
    };
  };

  serve.bundle = function(options) {
    var b, baseDir, bundle, expose, k, requirement, shims, transform, v, _i, _j, _len, _len1, _ref1, _ref2, _ref3;

    baseDir = dirname(resolve(options.entry));
    b = browserify({
      entries: [options.entry],
      extensions: options.extensions
    });
    b.delay = options.bundleDelay || 300;
    if (options.shims != null) {
      shims = {};
      _ref1 = options.shims;
      for (k in _ref1) {
        v = _ref1[k];
        shims[k] = extend({}, v, {
          path: join(baseDir, v.path)
        });
      }
      b = shim(b, shims);
    }
    if (options.transforms != null) {
      _ref2 = options.transforms;
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        transform = _ref2[_i];
        b.transform(transform);
      }
    }
    if (options.requirements != null) {
      _ref3 = options.requirements;
      for (_j = 0, _len1 = _ref3.length; _j < _len1; _j++) {
        requirement = _ref3[_j];
        expose = relativize(options.entry, requirement);
        b.require(requirement, {
          expose: expose
        });
      }
    }
    if (options.bundle != null) {
      bundle = options.bundle(bundle);
    }
    return b;
  };

  serve.serve = serve;

}).call(this);

/*
//@ sourceMappingURL=index.map
*/
